### ISSUE TITLE
Exception when calling Optic.draw()

### ISSUE THREAD

**Issue by rjmoerland** [HarrisonKramer/optiland#338]
### Checklist

- [x] I have searched the [existing issues](https://github.com/HarrisonKramer/optiland/issues) and [discussions](https://github.com/HarrisonKramer/optiland/discussions) for a similar question or problem.
- [x] I have read the [documentation](https://optiland.readthedocs.io/en/latest/) and tried to find an answer there.
- [x] I am using the **latest version** of Optiland (if not, please update and retry).
- [x] I have tried to reproduce or debug the issue myself before opening this.
- [x] I have included **all necessary context**, such as version info, error messages, or minimal reproducible examples.

### Bug Report
The bug occurs with an up-to-date editable install of Optiland, on the `master` branch: when loading the attached Optiland [file](https://github.com/user-attachments/files/22581948/objective.json), the method `Optic.draw()` throws an `AttributeError`: `AttributeError: 'NoneType' object has no attribute 'get_ray_origins'`. The exception is *not* thrown when using version 0.5.6. I have used `git bisect` to find the first commit where the exception is thrown, which is [5acf61f](https://github.com/HarrisonKramer/optiland/commit/5acf61f323a87e36e2d84e1d6ced809e67f49014). 

It is very possible that this is something I did wrong, since I've just begun to use Optiland. I have tried to create a simpler example, but the built-in samples work just fine. The Optiland file was created from an imported Zemax file that needed some editing by hand before it was properly(?) imported. The underlying issue was a missing glass type, but I substituted it for another that is part of the Optiland glass catalog.

**To Reproduce**
1. Execute the following code:
```
import numpy as np
from optiland import optic
from optiland.fileio import load_optiland_file

lens = load_optiland_file("objective.json")
lens.draw()
```
2. Exception is thrown

**Expected behavior**
The following image to be drawn:

<img width="908" height="299" alt="Image" src="https://github.com/user-attachments/assets/3879aa50-c9d4-414f-9b76-acc10bad70ac" />

**Environment**  
- Optiland Version: `0.5.6` and `master:5eedaf1`
- Python Version: `3.13.7`
- OS: `Windows`
- Additional Info: -

**Additional context**
[objective.json](https://github.com/user-attachments/files/22581948/objective.json)

**Comment by rjmoerland** [comment]
Cool, thank you so much!
